[tool.poetry]
name = "glory135-math"
version = "0.1.0"
description = ""
authors = ["Adeyemi Glory <79275377+Glory135@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
